### ISSUE TITLE
What about UIControl?

### ISSUE THREAD

**Issue by wangtian076** [mta452/UIView-TouchHighlighting#1]
or UIButton

**Comment by mta452** [comment]
UIButton is already a special purpose class and although UIControl can also have multiple subviews, apple recommends to subclass it for creating custom controls. The purpose of UIView+TouchHighlighting is to facilitate the conversion of existing views into buttons simply by setting the touch highlighting style and by adding a tap gesture recognizer.

**Comment by mta452** [comment]
MTCompoundButton has been added in v1.2 which inherits from UIControl.
